### ISSUE TITLE
Provide example search_filter using complex operators

### ISSUE THREAD

**Issue by jburos** [salesforce-marketingcloud/FuelSDK-Python#31]
I am looking for an example of using the FuelSDK to query Clicks & Opens using a complex filter object to pull data for a range of dates (EventDate <= a date and >= to a date). 

Specifically, consider the following line from a current sample (
https://github.com/ExactTarget/FuelSDK-Python/blob/master/objsamples/sample_openevent.py ) :

``` python
  getOpenEvent.search_filter = {'Property' : 'EventDate','SimpleOperator' : 'greaterThan','DateValue' : retrieveDate}
```

Can an example be provided of what this might look like to pull data for open events between two dates? 

Per issue #25, I believe complex operators are now supported but I am not sure how to use them.

**Comment by kartiksayee** [comment]
Hey, Below is the similar code but somehow this does not work. Can you please help?
fromDate = '2015-01-01T00:00:00'
    toDate = '2015-01-03T00:00:00'
 fromFilter = {'Property' : 'EventDate','SimpleOperator' : 'greaterThan','DateValue' : fromDate}
    toFilter = {'Property' : 'EventDate','SimpleOperator' : 'lessThan','DateValue' : toDate}
    getSentEvent.search_filter = {'LeftOperand' : fromFilter  , 'LogicalOperator': 'between', 'RightOperand' : toFilter}
    print getSentEvent.search_filter
    getResponse = getSentEvent.get()

**Comment by BrianEdwardHoover** [comment]
Change the LogicalOperator of your serach_filter to 'and' instead of 'between'.

**Comment by kartiksayee** [comment]
Sorry I tried that as well. And the code times out after sometime. Does not work with AND as well.

**Comment by kartiksayee** [comment]
Is there any other solution to this?

**Comment by BrianEdwardHoover** [comment]
Here are the relevant bits from my code which works just fine:
---
endDt = datetime.now()
startDt = endDt-timedelta(days=2)
filter_start={'Property':'DateTime', 'SimpleOperator':'greaterThan', 'DateValue':startDt}
filter_end = {'Property':'DateTime', 'SimpleOperator':'lessThan', 'DateValue':endDt}
complex_filter = {'LeftOperand': filter_start, 'LogicalOperator':'AND', 'RightOperand':filter_end}

deRows = ET_DataExtension_Row()
deRows.search_filter = complex_filter
---
If you are experiencing a timeout, perhaps the filter is still too open for the data set being queried.

**Comment by kartiksayee** [comment]
your code and my code are the same but somehow it does not work for me at all.

**Comment by kartiksayee** [comment]
Any other comments?

**Comment by BrianEdwardHoover** [comment]
Here is a full script which works just fine.  Try running this yourself and see what you encounter:

#! /usr/bin/env python

from FuelSDK import *
myClient = ET_Client()
sentevent = ET_SentEvent()
sentevent.auth_stub = myClient
startEventDate_filter =  {'Property' : 'EventDate','SimpleOperator' : 'greaterThan','DateValue' : '2015-07-01T00:00:00.000000'}
endEventDate_filter =  {'Property' : 'EventDate','SimpleOperator' : 'lessThan','DateValue' : '2015-07-30T T00:00:00.000000'}
sentevent.search_filter = {'LeftOperand': startEventDate_filter, 'LogicalOperator':'AND', 'RightOperand':endEventDate_filter}
results = sentevent.get()
print str(results.results)

**Comment by abhinav1630** [comment]
> Here is a full script which works just fine. Try running this yourself and see what you encounter:
> 
> #! /usr/bin/env python
> 
> from FuelSDK import *
> myClient = ET_Client()
> sentevent = ET_SentEvent()
> sentevent.auth_stub = myClient
> startEventDate_filter = {'Property' : 'EventDate','SimpleOperator' : 'greaterThan','DateValue' : '2015-07-01T00:00:00.000000'}
> endEventDate_filter = {'Property' : 'EventDate','SimpleOperator' : 'lessThan','DateValue' : '2015-07-30T T00:00:00.000000'}
> sentevent.search_filter = {'LeftOperand': startEventDate_filter, 'LogicalOperator':'AND', 'RightOperand':endEventDate_filter}
> results = sentevent.get()
> print str(results.results)

What if I have 2 more simple operands. How to connect them?
Lets suppose : 
startEventDate_filter = {'Property' : 'EventDate','SimpleOperator' : 'greaterThan','DateValue' : '2015-07-01T00:00:00.000000'}
endEventDate_filter = {'Property' : 'EventDate','SimpleOperator' : 'lessThan','DateValue' : '2015-07-30T T00:00:00.000000'}
startEventDate_filter_2 = {'Property' : 'EventDate','SimpleOperator' : 'greaterThan','DateValue' : '2015-07-01T00:00:00.000000'}
endEventDate_filter_2 = {'Property' : 'EventDate','SimpleOperator' : 'lessThan','DateValue' : '2015-07-30T T00:00:00.000000'}

In this case we have 2 start and end dates. How can we connect them in a single line?

**Comment by PranjalSharma22** [comment]
@abhinav1630 Did you get the solution of this?

I am also not getting how to include more than 2 filters while using search_filter since there are two options i.e Leftoperand and RightOperand. I also tried nesting these filters but that also didn't worked.

Thanks in advance if anyone could answer this query.

**Comment by abhinav1630** [comment]
@PranjalSharma22  Yes I was able to do it.
There is an option to Join 2 queries.

**Comment by PranjalSharma22** [comment]
@abhinav1630 Thanks for responding!
Could you please give one example of this option to join 2 queries or how exactly you joined 2 queries?
