### ISSUE TITLE
Is that ready for Python 3?

### ISSUE THREAD

**Issue by zhongdai** [salesforce-marketingcloud/FuelSDK-Python#60]
The suds is a problem, and I just comment out everything about Suds and Suds-patch, then it works.

But I just found many Python 2 in the code, 
- print used as a statement but not a function
- iteritems() used, but which retired in Python 3
- has_value() used, but should not use for Python 3

Is this package officially ready for Python 3? Or only for Python 2?

**Comment by nxorable** [comment]
The Python 3 branch has been released
https://github.com/salesforce-marketingcloud/FuelSDK-Python/tree/v1.0.0

**Comment by bachirelkhoury** [comment]
@nxorable that still uses iteritems() https://github.com/salesforce-marketingcloud/FuelSDK-Python/blob/v1.0.0/FuelSDK/objects.py#L300

**Comment by corby** [comment]
Bump!
Iteritems is forcing me to build my own module.

**Comment by amagar088** [comment]
Thanks for your effort. This has been taken care.

**Comment by bachirelkhoury** [comment]
@corby this was fixed in https://github.com/salesforce-marketingcloud/FuelSDK-Python/pull/76

**Comment by johnjiang** [comment]
Can we please get some investment into this package and release it officially for python 3?
